# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
    bash ~/miniconda.sh -b -p $HOME/miniconda
    eval "$(~/miniconda/bin/conda shell.bash hook)"
    cd "$(Build.BinariesDirectory)"
    git clone https://github.com/mslichao/md2docx
    cd md2docx
    pip install -r requirements.txt
  displayName: 'perpare env'

- script: |
    cd "$(Build.BinariesDirectory)/md2docx"
    python batchmd2docx.py "$(Build.SourcesDirectory)${mdpath}"
  displayName: 'build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/${mdpath}_docx'
    ArtifactName: 'drop'
    publishLocation: 'Container'