# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    alias python=python3
    python -V
    cd "$(Build.BinariesDirectory)"
    git clone https://github.com/mslichao/md2docx
    cd md2docx
    pip3 install --upgrade pip
    python3 batchmd2docx.py "$(Build.SourcesDirectory)/E-Challenge"
  displayName: 'build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)_docx'
    ArtifactName: 'drop'
    publishLocation: 'Container'