# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    python3 -V
    cd "$(Build.BinariesDirectory)"
    git clone https://github.com/mslichao/md2docx
    cd md2docx
    pip3 install --upgrade pip setuptools
    pip3 install -r requirements.txt
    python3 batchmd2docx.py "$(Build.SourcesDirectory)/B-教学案例与实践/B6-神经网络基本原理简明教程"
  displayName: 'build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)_docx'
    ArtifactName: 'drop'
    publishLocation: 'Container'